name: bin-dev-test
on:
  push:
    branches: [ bin-dev-branch ]
jobs:
  run-specific-tests:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Execute unit tests
      run: dotnet test

