# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    
    permissions:
      packages: write
      contents: read

    steps:
    - name: Login to GitHub Container Registry
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Pull docker image
      run: docker pull ghcr.io/battlegroundscoh/coh-battlegrounds-networking:latest
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: cd coh2-battlegrounds && dotnet restore
    - name: Build
      run: cd coh2-battlegrounds && dotnet build --no-restore
    - name: Test
      run: cd coh2-battlegrounds && dotnet test --no-build --verbosity normal
