name: Run integration tests

on:
  workflow_dispatch:

jobs:
  build-and-test:

    runs-on: windows-latest
    
    permissions:
      packages: read
      contents: read

    steps:
    - uses: actions/checkout@v6
      
    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: cd v2\Battlegrounds.Client && dotnet restore

    - name: Build and Test
      run: cd v2\Battlegrounds.Client && dotnet test --verbosity=n --filter=TestCategory=Integration
